apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata: 
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: semie/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.106.190.87"
              value: "auth-service.default"
        # - name: auth
        #   image: semie/kub-demo-auth:latest
        

